/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kullanicilar.Ekranlar;

import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import kullanicilar.KullaniciGirisi;

/**
 *
 * @author Rosegarden
 */
public class MusteriEkrani extends javax.swing.JFrame {

    String basliklar[] = {"Araba Kodu", "Araba Modeli", "Günlük Ücret", "Toplam Ücret", "Alım Tarihi", "Teslim Tarihi"};
    DefaultTableModel dtm2 = new DefaultTableModel();

    public MusteriEkrani() {
        initComponents();
        this.setTitle("Müşteri Ekranı");
        
        musteriKimlikTxt.setText(String.valueOf(kullanicilar.MusteriGiris.id));
       
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        resetDtm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        musteriKimlikTxt = new javax.swing.JTextField();
        arabaKiralaBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        alinanArabalarTable = new javax.swing.JTable();
        iadeBtn = new javax.swing.JButton();
        aldiklarimiGetirBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        musteriKimlikTxt.setEnabled(false);
        getContentPane().add(musteriKimlikTxt);
        musteriKimlikTxt.setBounds(570, 10, 140, 30);

        arabaKiralaBtn.setText("Araba Kirala");
        arabaKiralaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arabaKiralaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(arabaKiralaBtn);
        arabaKiralaBtn.setBounds(20, 10, 190, 30);

        alinanArabalarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(alinanArabalarTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 160, 530, 340);

        iadeBtn.setText("İade Et");
        iadeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iadeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(iadeBtn);
        iadeBtn.setBounds(570, 200, 140, 25);

        aldiklarimiGetirBtn.setText("Aldıklarımı Getir");
        aldiklarimiGetirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aldiklarimiGetirBtnActionPerformed(evt);
            }
        });
        getContentPane().add(aldiklarimiGetirBtn);
        aldiklarimiGetirBtn.setBounds(570, 160, 140, 25);

        setSize(new java.awt.Dimension(745, 573));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void arabaKiralaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arabaKiralaBtnActionPerformed
        // TODO add your handling code here:
        new ArabaKirala().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_arabaKiralaBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        String[] options = {"ÇIKIŞ", "İPTAL"};
        int i = JOptionPane.showOptionDialog(this, "Bu işlem sizi Kullanıcı Girişine götürür." + "\n" + "Tekrar Kullanıcı Seçimi yapmak için ekranına dönersiniz." + "\n" + "Devam etmek istiyormusunuz?", "Personel Girişinden Çıkış", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (i == 0) {
            this.setVisible(false);
            new KullaniciGirisi().setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private void iadeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iadeBtnActionPerformed
        // TODO add your handling code here:
        if (alinanArabalarTable.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(iadeBtn, "İade Etmek İçin Araba Seçiniz", "Seçim Yok Hatası", JOptionPane.WARNING_MESSAGE);
        } else {
            int arabaKodu = Integer.parseInt(alinanArabalarTable.getValueAt(alinanArabalarTable.getSelectedRow(), 0).toString());
            ArabaListesi iade = new ArabaListesi();
            iade.aracNo = Integer.parseInt(alinanArabalarTable.getValueAt(alinanArabalarTable.getSelectedRow(), 0).toString());
            iade.model = alinanArabalarTable.getValueAt(alinanArabalarTable.getSelectedRow(), 1).toString();
            iade.fiyat = Integer.parseInt(String.valueOf(alinanArabalarTable.getValueAt(alinanArabalarTable.getSelectedRow(), 2)));

            ArabaListesi.arabalarim.add(iade);
            for (int i = 0; i < AlinmisArabalar.musteriAlinanlar.size(); i++) {
                AlinmisArabalar item = AlinmisArabalar.musteriAlinanlar.get(i);
                if (arabaKodu == item.aracNo) {
                    AlinmisArabalar.musteriAlinanlar.remove(item);
                }
            }
            JOptionPane.showMessageDialog(iadeBtn, "İade işlemi gerçekleşmiştir...", "İade Onayı", JOptionPane.INFORMATION_MESSAGE);
            dtm2.removeRow(alinanArabalarTable.getSelectedRow());

        }
        resetDtm();
    }//GEN-LAST:event_iadeBtnActionPerformed

    private void aldiklarimiGetirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aldiklarimiGetirBtnActionPerformed
        // TODO add your handling code here:
        resetDtm();
        for (AlinmisArabalar alinmisListe : AlinmisArabalar.musteriAlinanlar) {
            if (alinmisListe.musteriID == kullanicilar.MusteriGiris.id) {
                dtm2.addRow(new Object[]{alinmisListe.aracNo, alinmisListe.alModel, alinmisListe.gunUcret, alinmisListe.TopUcret, alinmisListe.aTarih, alinmisListe.vTarih});
            }

        }


    }//GEN-LAST:event_aldiklarimiGetirBtnActionPerformed

    private void resetDtm() {
        dtm2 = new DefaultTableModel();
        dtm2.setColumnIdentifiers(basliklar);
        alinanArabalarTable.setModel(dtm2);
    }

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aldiklarimiGetirBtn;
    private javax.swing.JTable alinanArabalarTable;
    private javax.swing.JButton arabaKiralaBtn;
    private javax.swing.JButton iadeBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField musteriKimlikTxt;
    // End of variables declaration//GEN-END:variables
}
