/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kullanicilar.Ekranlar;

/**
 *
 * @author Rosegarden
 */
public class PersonelEkrani extends javax.swing.JFrame {

    /**
     * Creates new form PersonelEkrani
     */
    public PersonelEkrani() {
        initComponents();
        alinanArabalarPnl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alinanArabalarPnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alinanTable = new javax.swing.JTable();
        alinanArabalarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        alinanArabalarPnl.setLayout(null);

        alinanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(alinanTable);

        alinanArabalarPnl.add(jScrollPane1);
        jScrollPane1.setBounds(30, 40, 452, 256);

        getContentPane().add(alinanArabalarPnl);
        alinanArabalarPnl.setBounds(290, 140, 520, 330);

        alinanArabalarBtn.setText("Alınan Arabalar");
        alinanArabalarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alinanArabalarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(alinanArabalarBtn);
        alinanArabalarBtn.setBounds(650, 50, 121, 25);

        setSize(new java.awt.Dimension(850, 551));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void alinanArabalarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alinanArabalarBtnActionPerformed
        // TODO add your handling code here:
        alinanArabalarPnl.setVisible(true);
    }//GEN-LAST:event_alinanArabalarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonelEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alinanArabalarBtn;
    private javax.swing.JPanel alinanArabalarPnl;
    private javax.swing.JTable alinanTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
