/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package karsilama;

import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Rosegarden
 */
public class HosGeldiniz extends javax.swing.JFrame {

    /**
     * Creates new form HosGeldiniz
     */
    Icon resim = new ImageIcon("1.jpg");

    public HosGeldiniz() {
        initComponents();
        this.setTitle("HOŞGELDİNİZ");
        resimLbl.setIcon(resim);
        this.getContentPane().setBackground(Color.WHITE);
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hosgeldinLbl = new javax.swing.JLabel();
        resimLbl = new javax.swing.JLabel();
        devamEtBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        hosgeldinLbl.setBackground(new java.awt.Color(255, 255, 255));
        hosgeldinLbl.setFont(new java.awt.Font("Franklin Gothic Medium", 3, 61)); // NOI18N
        hosgeldinLbl.setForeground(new java.awt.Color(51, 204, 0));
        hosgeldinLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hosgeldinLbl.setText("HOŞGELDİNİZ !...");
        getContentPane().add(hosgeldinLbl);
        hosgeldinLbl.setBounds(100, 220, 490, 120);
        getContentPane().add(resimLbl);
        resimLbl.setBounds(140, 50, 376, 130);

        devamEtBtn.setBackground(new java.awt.Color(255, 255, 255));
        devamEtBtn.setForeground(new java.awt.Color(51, 204, 0));
        devamEtBtn.setText("Devam Et");
        devamEtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devamEtBtnActionPerformed(evt);
            }
        });
        getContentPane().add(devamEtBtn);
        devamEtBtn.setBounds(579, 370, 100, 25);

        setSize(new java.awt.Dimension(718, 447));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void devamEtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devamEtBtnActionPerformed
        // TODO add your handling code here:
        new kullanicilar.KullaniciGirisi().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_devamEtBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        String[] options = {"ÇIKIŞ", "İPTAL"};
        int i = JOptionPane.showOptionDialog(this, "Bu işlem sizin programdan çıkmanıza sebep olur." + "\n" + "Devam etmek istiyormusunuz?", "Programdan Çıkış", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (i == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HosGeldiniz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HosGeldiniz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HosGeldiniz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HosGeldiniz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HosGeldiniz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton devamEtBtn;
    private javax.swing.JLabel hosgeldinLbl;
    private javax.swing.JLabel resimLbl;
    // End of variables declaration//GEN-END:variables
}
