/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kullanicilar;

import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Rosegarden
 */
public class KullaniciGirisi extends javax.swing.JFrame {

    /**
     * Creates new form KullaniciGirisi
     */
    Icon resim = new ImageIcon("1.jpg");
    public KullaniciGirisi() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        resimLbl.setIcon(resim);
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resimLbl = new javax.swing.JLabel();
        personelGirisBtn = new javax.swing.JButton();
        musteriGirisBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(resimLbl);
        resimLbl.setBounds(160, 30, 376, 130);

        personelGirisBtn.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 23)); // NOI18N
        personelGirisBtn.setForeground(new java.awt.Color(51, 204, 0));
        personelGirisBtn.setText("Personel Girişi");
        personelGirisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelGirisBtnActionPerformed(evt);
            }
        });
        getContentPane().add(personelGirisBtn);
        personelGirisBtn.setBounds(80, 230, 260, 90);

        musteriGirisBtn.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 23)); // NOI18N
        musteriGirisBtn.setForeground(new java.awt.Color(51, 204, 0));
        musteriGirisBtn.setText("Müşteri Girişi");
        musteriGirisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteriGirisBtnActionPerformed(evt);
            }
        });
        getContentPane().add(musteriGirisBtn);
        musteriGirisBtn.setBounds(390, 230, 280, 90);

        setSize(new java.awt.Dimension(771, 502));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        String []options={"ÇIKIŞ","İPTAL"};
        int i = JOptionPane.showOptionDialog(this, "Bu işlem sizin programdan çıkmanıza sebep olur."+"\n"+"Devam etmek istiyormusunuz?", "Programdan Çıkış", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (i == 0) {
            this.setVisible(false);
            new karsilama.HosGeldiniz().setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private void personelGirisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelGirisBtnActionPerformed
        // TODO add your handling code here:
        new kullanicilar.PersonelGiris().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_personelGirisBtnActionPerformed

    private void musteriGirisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriGirisBtnActionPerformed
        // TODO add your handling code here:
        new kullanicilar.MüsteriGiris().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_musteriGirisBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(KullaniciGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(KullaniciGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(KullaniciGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(KullaniciGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new KullaniciGirisi().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton musteriGirisBtn;
    private javax.swing.JButton personelGirisBtn;
    private javax.swing.JLabel resimLbl;
    // End of variables declaration//GEN-END:variables
}
